import { join, resolve, dirname } from 'path';
import getFilesListRecursive from '../../shared/commands/getFilesListRecursive';
import {
    readFile,
    rm,
    readDir,
    writeFile,
} from '../../shared/io';

async function removeAutoGeneratedCode(config) {
    const { groupsPath } = config;
    const aGroupPath = join(resolve('.'), groupsPath);
    const groups = await getFilesListRecursive([aGroupPath]);

    await Promise.all(groups.map(async (group) => {
        const groupContents = await readFile(group, 'utf-8');

        if (groupContents.includes('/*GENERATED FILE*/')) {
            await rm(group);
        } else {
            const replaced = groupContents.replace(/\/\*GENERATED CODE\*\/[^;]*;\/\*GENERATED CODE END\*\//g, '');
            await writeFile(group, replaced);
        }

        const groupDirContent = await readDir(dirname(group));
        if (groupDirContent.length === 0) {
            await rm(dirname(group));
        }
    }));
}

export default removeAutoGeneratedCode;
