#!/usr/bin/env node

import { greet, logSuccess } from '../shared/logger';
import startApp from '../shared/commands/startApp';
import removeAutoGeneratedGroups from './commands/removeAutoGeneratedCode';

async function run(cfg) {
    greet('Cleaning project');
    await removeAutoGeneratedGroups(cfg);

    logSuccess('Cleaning project done');
}

startApp('images_atlas').then((runner) => runner(run));
