#!/usr/bin/env node

import { greet, logSuccess } from '../shared/logger';
import startApp from '../shared/commands/startApp';
import removeAutoGeneratedGroups from './commands/removeAutoGeneratedCode';

async function run(getConfigParamClbk) {
    greet('Cleaning project');

    const {
        groupsPath,
    } = getConfigParamClbk('groups');

    await removeAutoGeneratedGroups({ groupsPath });

    logSuccess('Cleaning project done');
}

startApp().then((runner) => runner(run));
